name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # - name: Add JCenter repository
      #   run: |
      #     echo "Adding JCenter repository to settings.gradle"
      #     if grep -q "allprojects" build.gradle; then
      #       # 如果使用旧式build.gradle配置
      #       sed -i '/allprojects {/,/repositories {/,/}/s/}$/\n        jcenter()\n    }/' build.gradle
      #     else
      #       # 如果使用新式settings.gradle配置
      #       sed -i '/dependencyResolutionManagement {/,/repositories {/,/}/s/}$/\n            jcenter()\n        }/' settings.gradle
      #     fi

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Build with Gradle
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4  # 使用最新的 v4 版本
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7  # 设置保留期限为7天
          compression-level: 9  # 最高压缩级别，节省空间
          overwrite: true  # 如果存在同名制品则覆盖